---
version: '3'

services:
    control-machine:
        image: ansible/ansible:centos7
        hostname: control-machine.loc
        volumes:
            - ./config:/etc/orchestration:ro

    target:
        build:
            context: ./
            dockerfile: ./target.Dockerfile
        hostname: target.loc
