---
version: '3'

services:
    control-machine:
        build:
            context: ./
            dockerfile: ./control.Dockerfile
        hostname: control-machine.loc
        volumes:
            - ./config:/etc/ansible

    target:
        build:
            context: ./
            dockerfile: ./target.Dockerfile
        hostname: target.loc
