---
- hosts: target

  vars_files:
    - vars/users.yml

  tasks:
    - name: Create users
      include_role:
        name: add_user
      vars:
        config: "{{user_config}}"
      loop: "{{users}}"
      loop_control:
        loop_var: user_config
