---
- hosts: target
  vars:
    user_name: devops
    user_id: 1000
    user_primary_group: devops
    user_primary_group_id: 1000
    user_authorized_key: "{{ lookup('file', '/etc/ansible/devops_rsa.pub') }}"
    user_home_dir: /home/devops

  tasks:
    - name: Create group
      group:
        name: "{{user_primary_group}}"
        gid: "{{user_primary_group_id}}"
      become: true

    - name: Create user
      user:
        uid: "{{user_id}}"
        group: "{{user_primary_group}}"
        home: "{{user_home_dir}}"
        name: "{{user_name}}"
      become: true

    - name: Copy key
      copy:
        src: /etc/ansible/devops_rsa.pub
        dest: "{{user_home_dir}}/.ssh/id_rsa.pub"
        owner: "{{user_name}}"
        mode: 0644

    - name: Disable requiretty
      template:
        src: sudoers.j2
        dest: /etc/sudoers
      become: true
