---
- hosts: target
  vars:
    user_name: devops
    user_id: 1000
    user_primary_group: devops
    user_primary_group_id: 1000
    user_authorized_key: "{{ lookup('file', '/etc/ansible/devops_rsa.pub') }}"
    user_home_dir: /home/devops

  tasks:
    - name: Create group
      command: /usr/sbin/groupadd
          --force
          --gid {{ user_primary_group_id }}
          {{ user_primary_group }}
      become: true

    - name: Create user
      shell: /usr/bin/id -u {{ user_name }} || /usr/sbin/useradd
          --gid {{ user_primary_group_id }}
          --uid {{ user_id }}
          --home-dir {{ user_home_dir }}
          {{ user_name }}
      become: true

    - name: Copy key
      shell: echo "{{ user_authorized_key }}"
        > {{ user_home_dir }}/.ssh/id_rsa.pub

    - name: Disable requiretty
      template:
        src: sudoers.j2
        dest: /etc/sudoers
      become: true
