---
- hosts: target
  vars:
    user_name: devops
    user_id: 1000
    user_primary_group: devops
    user_primary_group_id: 1000

  tasks:
    - name: Create group
      group:
        name: "{{user_primary_group}}"
        gid: "{{user_primary_group_id}}"
      become: true

    - name: Create user
      user:
        uid: "{{user_id}}"
        group: "{{user_primary_group}}"
        name: "{{user_name}}"
      become: true

    - name: Copy key
      authorized_key:
        user: "{{user_name}}"
        state: present
        key: "{{ lookup('file', '{{playbook_dir}}/{{user_name}}_rsa.pub') }}"

    - name: Ensure /etc/sudoers.d/ exists
      file:
        dest: /etc/sudoers.d/
        state: directory
      become: true

    - name: Ensure /etc/sudoers.d/ is enabled
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
      become: true

    - name: Config sudo
      template:
        src: "{{user_name}}.j2"
        dest: "/etc/sudoers.d/{{user_name}}"
        validate: '/usr/sbin/visudo -cf %s'
      become: true
